feat: Form & FormItem component
ikun-svelte/ikun-ui pull request #108
Opened 2023-08-19 15:38 UTC by moushicheng

## Preview
``` svelte
<script lang="ts">
	import { KForm, createKFormInstance, KFormItem } from '@ikun-ui/form';
	import { IKunFormInstance } from '@ikun-ui/utils';
        let form: IKunFormInstance = createKFormInstance();
</script>
<KForm bind:form>
	----Form----
	<KFormItem label={'name'} field={'name'}>
		<KInput placeholder="inputValue"></KInput>
	</KFormItem>
	<KFormItem label={'password'} field={'password'}>
		<KInput placeholder="inputValue"></KInput>
	</KFormItem>

	<KFormItem field={'obj'}>
		<KFormItem label={'a'} field={'a'}>
			<KInput placeholder="inputValue"></KInput>
		</KFormItem>
		<KFormItem label={'b'} field={'b'}>
			<KInput placeholder="inputValue"></KInput>
		</KFormItem>
	</KFormItem>

	<KButton on:click={() => console.log(form.submit())}>Submit</KButton>
	<KButton
		on:click={() => {
			form.setValues({ name: 'ikun', password: '1145142333', obj: { a: 1, b: 2 } });
		}}>setValue</KButton
	>
	----Form----
</KForm>
```
## Support:
- form.setValue & form.setValues to set form value (it can use fill form)
- nested FormItem 
such as: 
```html
// now form.values==={obj:{a:inputValue,b:inputValue}}
 	<KFormItem field={'obj'}>
		<KFormItem label={'a'} field={'a'}>
			<KInput placeholder="inputValue"></KInput>
		</KFormItem>
		<KFormItem label={'b'} field={'b'}>
			<KInput placeholder="inputValue"></KInput>
		</KFormItem>
	</KFormItem>
```
- input 

## TODO:
- form validate 
- support Form components(Switch,CheckBox) to use inside FormItem
 (only need to bind the field bidirectionally)
```svelte
<script>
//dom -> field
 	const onUpdated = (e: Event) => {
              //....
	     formContext?.updateField((e.target as HTMLInputElement).value);
	};
//field -> dom
        formContext?.subscribe((value: any) => (valueInner = value));
</script>
```
- and so on.....

2023-08-22 04:21 UTC, baiwusanyu-c requested changes

2023-08-22 04:21 UTC, baiwusanyu-c commented on components/Form/src/helper.ts
> +			if (args.length === 0) throw new Error('subscribe need at least one argument');
Can you explain the specific scenario of the two branches of `arguments.length === 1` and `arguments.length === 2` ? I don't quite understand why this is necessary

2023-08-22 11:05 UTC, moushicheng commented on components/Form/src/helper.ts
> +			if (args.length === 0) throw new Error('subscribe need at least one argument');
```ts
// get values.userInfo.userName
subscribe('userInfo.userName',(value)=>{
    console.log(value) //baiwusanyu-c
})

// get all values
subscribe((value)=>{
// {
//   userInfo: {
//     username: 'baiwusanyu-c',
//     anotherField: '...'
//   },
// }
    console.log(value)
})
```

2023-08-22 11:20 UTC, moushicheng commented on components/Form/src/helper.ts
> +			if (args.length === 0) throw new Error('subscribe need at least one argument');
可以直接加我微信moushichengw，小问题直接微信里速聊

2023-08-23 14:52 UTC, moushicheng commented on components/Form/src/helper.ts
> +			if (args.length === 0) throw new Error('subscribe need at least one argument');
Maybe,i can change this logic
just function subscribe(path,callback)
when path==='*',subscribe will fill all values
when path==='another path' ,subscribe will fill specific value,
I think it makes more sense

2023-08-29 06:29 UTC, zhangmo8 commented
I think Maybe need a InitValue for this createKFormInstance();
Maybe like 

```
let form: IKunFormInstance = createKFormInstance({initialValues: {}});
```

2023-08-29 15:44 UTC, moushicheng commented
> I think Maybe need a InitValue for this createKFormInstance(); Maybe like
> 
> ```
> let form: IKunFormInstance = createKFormInstance({initialValues: {}});
> ```

2023-08-31 08:01 UTC, songjianet requested changes

2023-08-31 08:01 UTC, songjianet commented on components/Switch/src/index.svelte
>  	 */
Please use english.

2023-09-02 02:28 UTC, moushicheng commented on components/Switch/src/index.svelte
>  	 */
done

2023-09-26 13:45 UTC, baiwusanyu-c commented on components/Form/src/helper.ts
> +		callback(currentContext);
这个为什么不和重置一样，只对anotherNodesKeys.length === 0的上下文对象调用验证函数？

2023-09-30 01:16 UTC, moushicheng commented on components/Form/src/helper.ts
> +		callback(currentContext);
因为FormItem可以嵌套，我们可以设想这么一个结构
```
  Form
    - FormItem.a
        - FormItem.a1
        - FormItem.a2
    - FormItem.b
```
有anotherNodesKeys.length === 0的情况， 意味着只遍历没有子节点的Context，在这个结构里只会遍历到a1、a2、b这类边缘节点。

如果没有anotherNodesKeys.length === 0，则a，a1，a2，b都会遍历到
validateValues需要遍历所有节点（a,a1,a2,b）,这是因为用户可能在FormItem.a上设置rules（校验规则），我们允许直接在a上写rules。

而像resetValues（重置所有字段） 我们只需要重置a1，a2和b 这些边缘节点就好了，因为如果重置了a1，a2，再去重置a是冗余操作。

2023-09-30 01:32 UTC, moushicheng commented on components/Form/src/helper.ts
> +		callback(currentContext);
顺带一提，当时调研validate用什么库，我最终选择了valibot这个库，如果有不妥的地方我们可以再讨论讨论

2023-09-30 02:42 UTC, moushicheng commented on components/Form/src/helper.ts
> +		if (node.__FormContext__) return;
```
 Form
    - FormItem.a
        - FormItem.a1
        - FormItem.a2
```
这样的Form转化过来的Context的实际结构
{
   __this__: FormContext a
   a1:{
      __this__: FormContext a1
   }
   a2:{
     __this:__: FormContext a2
   }
}
如果不判断if(node.__FormContext__)
遍历第一层则会遍历到三个属性__this__,a1,a2但这并不是FormContext结构。

2023-10-08 03:55 UTC, baiwusanyu-c commented on components/Form/src/helper.ts
> +		callback(currentContext);
> validateValues需要遍历所有节点（a,a1,a2,b）,这是因为用户可能在FormItem.a上设置rules（校验规则），我们允许直接在a上写rules。
我理解在整个数据结构上肯能是 const form = { a: {a1:‘xxx’, a2: 'xxx'}, b: 'xxx'}, 我无法想象在对a1 和 a2 进行校验后还需要对 a 做什么样的校验

2023-10-08 03:58 UTC, baiwusanyu-c commented on components/Form/src/helper.ts
> +		callback(currentContext);
> 顺带一提，当时调研validate用什么库，我最终选择了valibot这个库，如果有不妥的地方我们可以再讨论讨论

valibot 库有什么优势？作为组件，我们只需要封装非空校验，复杂的校验应该由用户去完成，也就是说我认为应该让用户去使用 valibot  ，而不是把它加入到组件库中

2023-10-08 08:18 UTC, moushicheng commented on components/Form/src/helper.ts
> +		callback(currentContext);
白雾三语姐有微信不，感觉微信讨论方便点 moushichengw 通过这个id可以加我

2023-10-08 08:22 UTC, moushicheng commented on components/Form/src/helper.ts
> +		callback(currentContext);
> > validateValues需要遍历所有节点（a,a1,a2,b）,这是因为用户可能在FormItem.a上设置rules（校验规则），我们允许直接在a上写rules。
> 
> 我理解在整个数据结构上可能是 const form = { a: {a1:‘xxx’, a2: 'xxx'}, b: 'xxx'}, 我无法想象在对a1 和 a2 进行校验后还需要对 a 做什么样的校验

主要是允许用户在任意FormItem上写rules都生效，否则某用户直接在a上写rules，而a1和a2的rules===undefined的情况下，交验逻辑会失效

2023-11-14 06:08 UTC, merged