refactor: optimize switch
ikun-svelte/ikun-ui pull request #156
Opened 2023-08-28 08:38 UTC by a145789

使用 switch 的时候value 的typescript类型错误，看了下源码，想试着优化下逻辑

2023-08-28 10:10 UTC, baiwusanyu-c commented
可以简述一下改动的逻辑吗

2023-08-28 10:14 UTC, baiwusanyu-c approved these changes

2023-08-29 01:05 UTC, a145789 commented
主要是对于 `checkedValue` 和 `unCheckedValue` 默认值为 `undefined` 的情况。如果 `value` 在默认情况下为布尔值，那么 `checkedValue` 和 `unCheckedValue` 可默认为 `true` 和 `false`，可以减少对 `undefined` 的判断。`innerState` 也变成一个只读值，只表示当前是否为选中状态，不再需要手动同步状态。

2023-08-29 02:04 UTC, vtrbo requested changes
当属性或类型发生变化时，需要同步更新文档。

2023-08-29 08:52 UTC, vtrbo approved these changes

2023-08-29 08:53 UTC, merged