feat: added input three size
ikun-svelte/ikun-ui pull request #246
Opened 2023-09-13 06:53 UTC by vtrbo

2023-09-13 14:26 UTC, baiwusanyu-c requested changes
How about adding a test for `isError` and `errorMsg `which will be used in the Form component

2023-09-14 01:46 UTC, songjianet requested changes

2023-09-14 01:46 UTC, songjianet commented on components/Input/__test__/input.spec.ts
> +
Maybe it would be better to combine all size tests into one test. ['sm', 'md', 'lg'].forEach(s => {})

2023-09-14 07:39 UTC, baiwusanyu-c requested changes
![image](https://github.com/ikun-svelte/ikun-ui/assets/32354856/b74a046f-46af-4f6b-b32f-9039802e952f)
https://deploy-preview-246--ikun-ui.netlify.app/components/KInput.html#input-slots

2023-09-14 07:40 UTC, baiwusanyu-c commented
![image](https://github.com/ikun-svelte/ikun-ui/assets/32354856/35f24861-ad72-4031-a068-8e72b4dcea06)
https://deploy-preview-246--ikun-ui.netlify.app/components/KInput.html#sizes

crowded

2023-09-14 09:07 UTC, baiwusanyu-c approved these changes

2023-09-14 09:07 UTC, merged